// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChiTieu_3TL.Data;

#nullable disable

namespace QuanLyChiTieu_3TL.Migrations
{
    [DbContext(typeof(QuanLyChiTieu3tlContext))]
    [Migration("20250722181054_mi2")]
    partial class mi2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChiTieu_3TL.Data.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiDanhMuc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DanhMuc__3214EC07A011E51C");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu_3TL.Data.GiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("NgayGiaoDich")
                        .HasColumnType("date");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__GiaoDich__3214EC07CDE51CC7");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("GiaoDich", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu_3TL.Data.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC074873427D");

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D10534E0599D9B")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu_3TL.Models.user", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("QuanLyChiTieu_3TL.Data.GiaoDich", b =>
                {
                    b.HasOne("QuanLyChiTieu_3TL.Data.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("IdDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__GiaoDich__IdDanh__4E88ABD4");

                    b.HasOne("QuanLyChiTieu_3TL.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("IdTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK__GiaoDich__IdTaiK__4F7CD00D");

                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("QuanLyChiTieu_3TL.Data.DanhMuc", b =>
                {
                    b.Navigation("GiaoDiches");
                });

            modelBuilder.Entity("QuanLyChiTieu_3TL.Data.TaiKhoan", b =>
                {
                    b.Navigation("GiaoDiches");
                });
#pragma warning restore 612, 618
        }
    }
}
